services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-app
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    networks:
      - airport-network

networks:
  airport-network:
    driver: bridge
